name: CI Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install Dependencies for Frontend
        run: |
          cd frontend
          npm install

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install Dependencies for Backend
        run: |
          cd backend
          npm install
